### ISSUE TITLE
Add gif of app UI

### ISSUE THREAD

**Issue by imjog** [imjog/technex-ios#2]
There is screenshots available on README.md. For understanding UI clearly there should be Gif of app functioning like most cocoapods have. You can use QuickTime Player for screen recording. After recording convert it into gif.

**Comment by Arya04** [comment]
so you want to make a gif of all the screenshots in the readme?

**Comment by imjog** [comment]
@Arya04 No, we don't want gif of all screenshot in readme. Have you seen preview of any cocoapods. Please go through any cocoapod git repo, you will know what exactly we want. Thanks :)
![preview](https://user-images.githubusercontent.com/20956124/31489634-ecbd235e-af5e-11e7-9f47-d9c080928084.gif)
